development:
  adapter: postgresql
  encoding: unicode
  database: ucbpblmembersportal_development

test:
  adapter: postgresql
  encoding: unicode
  database: ucbpblmembersportal_test

production:
  adapter: postgresql
  encoding: unicode
  database: ucbpblmembersportal_production
